"""create matches table

Revision ID: 5b50b2746cf2
Revises: 
Create Date: 2026-09-07 17:28:01.391190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b50b2746cf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('winner', sa.String(length=5), nullable=True),
    sa.Column('move_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("winner IN ('red', 'green', 'draw') OR winner IS NULL", name='check_match_winner'),
    sa.CheckConstraint('move_count BETWEEN 0 AND 9', name='check_match_move_count'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
