"""create moves table

Revision ID: a41a29d52bf1
Revises: 5b50b2746cf2
Create Date: 2026-09-07 19:01:25.521872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41a29d52bf1'
down_revision: Union[str, Sequence[str], None] = '5b50b2746cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=5), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint("player IN ('red', 'green')", name='check_move_player'),
    sa.CheckConstraint('position BETWEEN 0 AND 8', name='check_move_position'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'position', name='unique_position_per_match')
    )
    op.create_index(op.f('ix_moves_match_id'), 'moves', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moves_match_id'), table_name='moves')
    op.drop_table('moves')
    # ### end Alembic commands ###
